const CHAT_CREATED = "CHAT_CREATED";
const NEW_MESSAGE = "NEW_MESSAGE";
const JOIN_CHAT = "JOIN_CHAT";
const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
const AUTOMATIC_MESSAGE = "AUTOMATIC_MESSAGE";
const UPDATE_CHAT = "UPDATE_CHAT";
const MARK_READ = "MARK_READ";
const ON_ACTIVE = "ON_ACTIVE";
const INACTIVE = "INACTIVE";
const TYPING = "TYPING";
const STOP_TYPING = "STOP_TYPING";
const RECEIVE_IMAGE = "RECEIVE_IMAGE";

module.exports = {
  CHAT_CREATED,
  NEW_MESSAGE,
  JOIN_CHAT,
  RECEIVE_MESSAGE,
  AUTOMATIC_MESSAGE,
  UPDATE_CHAT,
  MARK_READ,
  ON_ACTIVE,
  INACTIVE,
  TYPING,
  STOP_TYPING,
  RECEIVE_IMAGE
};
