export const otherProducts = {
    "Joker": "joker",
    "Habanero": "habanero",
    "Playtech": "playtech",
    "JDB": "jdb",
    "SPADE GAMING": "spadegaming",
    "Jili": "jili",
    "LIVE22": "live22",
    "Pragmatic": "pragmatic",
    "VPOWER": "vpower",
    "XE88": "XE88",
    // "3win8": "3win8",
    "Asia Gaming": "ag",
    "BETSOFT": "betsoft",
    "CQ9": "cq9",
    "DREAMTECH": "dreamtech",
    "KMG": "kmg",
    // "QTECH": "qtech",
    "NextSpin": "nextspin",
    "Evo888h5" : "evo888h5",
    "PG SOFT": "pgsoft",
  };